"""Emit the lexicon as LIFT (Lexicon Interchange FormaT) — the FLEx-native XML for importing a lexicon.

LIFT holds the LEXICON only: one `<entry>` per lexeme (stems = lemmas; bound morphemes = affixes, carried
with a `morph-type` trait), each with `<grammatical-info>` (PartOfSpeech) and `<sense>`s (real glosses).
It does NOT hold inflected wordforms (those are generated by the morphology) nor the inflectional
templates / phonological rules (those live in the FLEx grammar / HC config). So this is the lexeme half of
the gold; `grammar_rules.jsonl` + `phonology.jsonl` are the grammar half, and `wordforms.jsonl` is the
analysis gold.
"""

from __future__ import annotations

import uuid
from pathlib import Path
from xml.sax.saxutils import escape

_NS = uuid.UUID("00000000-0000-0000-0000-0000600d5e70")  # fixed namespace → deterministic, diff-stable guids
PAIR_LANG = {"spa": "es", "ind": "id", "tgl": "tl", "swh": "sw"}


def _guid(s: str) -> str:
    return str(uuid.uuid5(_NS, s))


def _entry(word: str, pos: str, senses: list[str], morph_type: str, lang: str) -> str:
    gi = f'<grammatical-info value="{escape(pos)}"/>' if pos and pos != "Unknown" else ""
    sense_xml = ""
    for i, s in enumerate(senses or [""]):
        gloss = f'<gloss lang="en"><text>{escape(s)}</text></gloss>' if s else ""
        sense_xml += f'<sense id="{escape(word)}_{i}" guid="{_guid(word + "#" + str(i))}">{gi}{gloss}</sense>'
    return (
        f'<entry id="{escape(word)}" guid="{_guid(word)}">'
        f'<lexical-unit><form lang="{lang}"><text>{escape(word)}</text></form></lexical-unit>'
        f'<trait name="morph-type" value="{morph_type}"/>'
        f"{sense_xml}</entry>"
    )


def write_lift(path: Path, pair: str, lex_entries: list[dict], affixes: list[dict] | None = None) -> int:
    """Write `lexicon.lift`: a stem entry per lemma + a bound-morpheme entry per affix. Returns #entries."""
    lang = PAIR_LANG.get(pair, pair)
    parts = [_entry(e["word"], e.get("pos", ""), e.get("senses", []), "stem", lang) for e in lex_entries]
    for a in affixes or []:
        mt = a.get("morph_type", "suffix")  # LIFT morph-type names match FLEx (prefix/suffix/infix)
        gloss = a.get("features", "") or ""
        parts.append(_entry(a["affix"], "", [gloss] if gloss else [], mt, lang))
    xml = ('<?xml version="1.0" encoding="utf-8"?>\n'
           '<lift version="0.13" producer="linguistic-assistant/golden">\n'
           + "\n".join(parts) + "\n</lift>\n")
    path.write_text(xml, encoding="utf-8")
    return len(parts)
